compare: main.cpp analysis.cpp analysis.h grade.cpp grade.h medavg.cpp medavg.h Student_info.cpp Student_info.h
	g++ -o compare main.cpp analysis.cpp analysis.h grade.cpp grade.h medavg.cpp medavg.h Student_info.cpp Student_info.h

